package AmazonTecApp;


/**
* AmazonTecApp/AmazonTec.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AmazonTec.idl
* Tuesday, November 21, 2017 3:26:13 AM CST
*/

public interface AmazonTec extends AmazonTecOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AmazonTec
