package AmazonTecApp;


/**
* AmazonTecApp/AmazonTecOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AmazonTec.idl
* Tuesday, November 21, 2017 3:26:13 AM CST
*/

public interface AmazonTecOperations 
{
  String obtenerMensaje (String mensaje);
  String altaUsuario (String email, String nombre, String direccion, String notarjeta, String tarjeta, String password, String telefono);
  String idCliente (String email);
  void actualizarInventario (String album, String cantidad);
  String infoDiscoVenta (String album);
  String nombreCliente (String id);
  String compra (String album, String cliente, String cantidad);
  String infoAlbum (String id);
  String verifyUser (String email, String password);
  String obtenerCanciones (String album);
  String obtenerArtista (String id);
  String obtenerId (String artista);
  String obtenerCosto (String id);
  String obtenerAlbums (String artista);
  String obtenerCatalogo ();
} // interface AmazonTecOperations
