package AmazonTecApp;


/**
* AmazonTecApp/AmazonTecHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AmazonTec.idl
* Tuesday, November 21, 2017 3:26:13 AM CST
*/

abstract public class AmazonTecHelper
{
  private static String  _id = "IDL:AmazonTecApp/AmazonTec:1.0";

  public static void insert (org.omg.CORBA.Any a, AmazonTecApp.AmazonTec that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AmazonTecApp.AmazonTec extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AmazonTecApp.AmazonTecHelper.id (), "AmazonTec");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AmazonTecApp.AmazonTec read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AmazonTecStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AmazonTecApp.AmazonTec value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AmazonTecApp.AmazonTec narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AmazonTecApp.AmazonTec)
      return (AmazonTecApp.AmazonTec)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AmazonTecApp._AmazonTecStub stub = new AmazonTecApp._AmazonTecStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AmazonTecApp.AmazonTec unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AmazonTecApp.AmazonTec)
      return (AmazonTecApp.AmazonTec)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AmazonTecApp._AmazonTecStub stub = new AmazonTecApp._AmazonTecStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
