package AmazonTecApp;


/**
* AmazonTecApp/AmazonTecPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AmazonTec.idl
* Tuesday, November 21, 2017 3:26:13 AM CST
*/

public abstract class AmazonTecPOA extends org.omg.PortableServer.Servant
 implements AmazonTecApp.AmazonTecOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("obtenerMensaje", new java.lang.Integer (0));
    _methods.put ("altaUsuario", new java.lang.Integer (1));
    _methods.put ("idCliente", new java.lang.Integer (2));
    _methods.put ("actualizarInventario", new java.lang.Integer (3));
    _methods.put ("infoDiscoVenta", new java.lang.Integer (4));
    _methods.put ("nombreCliente", new java.lang.Integer (5));
    _methods.put ("compra", new java.lang.Integer (6));
    _methods.put ("infoAlbum", new java.lang.Integer (7));
    _methods.put ("verifyUser", new java.lang.Integer (8));
    _methods.put ("obtenerCanciones", new java.lang.Integer (9));
    _methods.put ("obtenerArtista", new java.lang.Integer (10));
    _methods.put ("obtenerId", new java.lang.Integer (11));
    _methods.put ("obtenerCosto", new java.lang.Integer (12));
    _methods.put ("obtenerAlbums", new java.lang.Integer (13));
    _methods.put ("obtenerCatalogo", new java.lang.Integer (14));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AmazonTecApp/AmazonTec/obtenerMensaje
       {
         String mensaje = in.read_string ();
         String $result = null;
         $result = this.obtenerMensaje (mensaje);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // AmazonTecApp/AmazonTec/altaUsuario
       {
         String email = in.read_string ();
         String nombre = in.read_string ();
         String direccion = in.read_string ();
         String notarjeta = in.read_string ();
         String tarjeta = in.read_string ();
         String password = in.read_string ();
         String telefono = in.read_string ();
         String $result = null;
         $result = this.altaUsuario (email, nombre, direccion, notarjeta, tarjeta, password, telefono);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // AmazonTecApp/AmazonTec/idCliente
       {
         String email = in.read_string ();
         String $result = null;
         $result = this.idCliente (email);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // AmazonTecApp/AmazonTec/actualizarInventario
       {
         String album = in.read_string ();
         String cantidad = in.read_string ();
         this.actualizarInventario (album, cantidad);
         out = $rh.createReply();
         break;
       }

       case 4:  // AmazonTecApp/AmazonTec/infoDiscoVenta
       {
         String album = in.read_string ();
         String $result = null;
         $result = this.infoDiscoVenta (album);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // AmazonTecApp/AmazonTec/nombreCliente
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.nombreCliente (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // AmazonTecApp/AmazonTec/compra
       {
         String album = in.read_string ();
         String cliente = in.read_string ();
         String cantidad = in.read_string ();
         String $result = null;
         $result = this.compra (album, cliente, cantidad);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // AmazonTecApp/AmazonTec/infoAlbum
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.infoAlbum (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // AmazonTecApp/AmazonTec/verifyUser
       {
         String email = in.read_string ();
         String password = in.read_string ();
         String $result = null;
         $result = this.verifyUser (email, password);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // AmazonTecApp/AmazonTec/obtenerCanciones
       {
         String album = in.read_string ();
         String $result = null;
         $result = this.obtenerCanciones (album);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // AmazonTecApp/AmazonTec/obtenerArtista
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.obtenerArtista (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 11:  // AmazonTecApp/AmazonTec/obtenerId
       {
         String artista = in.read_string ();
         String $result = null;
         $result = this.obtenerId (artista);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 12:  // AmazonTecApp/AmazonTec/obtenerCosto
       {
         String id = in.read_string ();
         String $result = null;
         $result = this.obtenerCosto (id);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 13:  // AmazonTecApp/AmazonTec/obtenerAlbums
       {
         String artista = in.read_string ();
         String $result = null;
         $result = this.obtenerAlbums (artista);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 14:  // AmazonTecApp/AmazonTec/obtenerCatalogo
       {
         String $result = null;
         $result = this.obtenerCatalogo ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AmazonTecApp/AmazonTec:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AmazonTec _this() 
  {
    return AmazonTecHelper.narrow(
    super._this_object());
  }

  public AmazonTec _this(org.omg.CORBA.ORB orb) 
  {
    return AmazonTecHelper.narrow(
    super._this_object(orb));
  }


} // class AmazonTecPOA
