package AmazonTecApp;

/**
* AmazonTecApp/AmazonTecHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from AmazonTec.idl
* Tuesday, November 21, 2017 3:26:13 AM CST
*/

public final class AmazonTecHolder implements org.omg.CORBA.portable.Streamable
{
  public AmazonTecApp.AmazonTec value = null;

  public AmazonTecHolder ()
  {
  }

  public AmazonTecHolder (AmazonTecApp.AmazonTec initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AmazonTecApp.AmazonTecHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AmazonTecApp.AmazonTecHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AmazonTecApp.AmazonTecHelper.type ();
  }

}
